### ISSUE TITLE
displaying in jupyter notebook

### ISSUE THREAD

**Issue by Fil** [Chilipp/psyplot#2]
thank you for the note about `p.show()`

however in my setup, it seems that it works only once:

<img width="539" alt="capture d ecran 2017-08-17 a 11 43 33" src="https://user-images.githubusercontent.com/7001/29406474-79170422-8341-11e7-8aeb-0d4eea28e8ec.png">

**Comment by Chilipp** [comment]
Hi @Fil,
thanks for your comment. The reason for this is that by default, the `inline` backend closes the figures after they have been shown in the notebook. Jupyter notebook just exports all open matplotlib figures as PNGs, closes the figures and displays the exported images in the browser. Therefore, as stated in the [docs](http://psyplot.readthedocs.io/en/latest/getting_started.html), you should include in the beginning the following lines

```python
%config InlineBackend.close_figures = False
```
This prevents that the figures are closed. The `p.show()` call then should display it.

Did this work for you?

**Comment by Fil** [comment]
>
> Did this work for you?
>

👌🏼
